services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ziad
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ziad:admin@db:5432/mydb?schema=public
      PORT: 3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
       - /app/.next
      - /app/prisma
      

volumes:
  db-data:
