version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    container_name: my_postgres_test_new
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: ziad
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
   
